package FinanceManangementSystem.demo.Model;

import FinanceManangementSystem.demo.Enums.PaymentMethod;
import FinanceManangementSystem.demo.Enums.SalePaymentStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(
        name = "sale_payments",
        indexes = {

                // =====================================================
                // SALE
                // =====================================================

                @Index(
                        name = "idx_sale_payment_sale",
                        columnList = "sale_id"
                ),

                // =====================================================
                // PAYMENT DATE
                // =====================================================

                @Index(
                        name = "idx_sale_payment_date",
                        columnList = "payment_date"
                ),

                // =====================================================
                // PAYMENT NUMBER
                // =====================================================

                @Index(
                        name = "idx_sale_payment_number",
                        columnList = "payment_number"
                ),

                // =====================================================
                // PAYMENT STATUS
                // =====================================================

                @Index(
                        name = "idx_sale_payment_status",
                        columnList = "payment_status"
                )
        }
)
public class SalePayment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // =========================================================
    // PUBLIC ID
    // =========================================================

    @UuidGenerator
    @Column(
            name = "public_id",
            nullable = false,
            unique = true,
            updatable = false
    )
    private UUID publicId;


    // =========================================================
    // SALE
    // =========================================================

    @ManyToOne(
            fetch = FetchType.LAZY,
            optional = false
    )
    @JoinColumn(
            name = "sale_id",
            nullable = false
    )
    private Sale sale;


    // =========================================================
    // PAYMENT NUMBER
    // =========================================================

    /*
     * Generated by DocumentSequenceService.
     *
     * Example:
     *
     * SALE_PAYMENT-2026-000001
     */

    @Column(
            name = "payment_number",
            nullable = false,
            unique = true,
            length = 40,
            updatable = false
    )
    private String paymentNumber;


    // =========================================================
    // PAYMENT AMOUNT
    // =========================================================

    @Column(
            name = "amount",
            nullable = false,
            precision = 15,
            scale = 2
    )
    private BigDecimal amount;


    // =========================================================
    // PAYMENT METHOD
    // =========================================================

    /*
     * Common PaymentMethod enum is used by:
     *
     * PurchasePayment
     * SalePayment
     */

    @Enumerated(EnumType.STRING)
    @Column(
            name = "payment_method",
            nullable = false,
            length = 30
    )
    private PaymentMethod paymentMethod;


    // =========================================================
    // PAYMENT REFERENCE
    // =========================================================

    /*
     * Optional:
     *
     * UPI transaction ID
     * Cheque number
     * Bank reference number
     * etc.
     */

    @Column(
            name = "reference_number",
            length = 100
    )
    private String referenceNumber;


    // =========================================================
    // PAYMENT DATE
    // =========================================================

    @Column(
            name = "payment_date",
            nullable = false
    )
    private LocalDate paymentDate = LocalDate.now();


    // =========================================================
    // PAYMENT STATUS
    // =========================================================

    /*
     * Controlled by SalePaymentService.
     *
     * It should NOT come from RequestSalePaymentDTO.
     *
     * New payment:
     *
     * PENDING / COMPLETED
     *
     * Cancelled payment:
     *
     * CANCELLED
     */

    @Enumerated(EnumType.STRING)
    @Column(
            name = "payment_status",
            nullable = false,
            length = 20
    )
    private SalePaymentStatus paymentStatus =
            SalePaymentStatus.PAID;


    // =========================================================
    // NOTES
    // =========================================================

    @Column(
            length = 500
    )
    private String notes;


    // =========================================================
    // AUDIT
    // =========================================================

    @CreationTimestamp
    @Column(
            nullable = false,
            updatable = false
    )
    private LocalDateTime createdAt;


    @UpdateTimestamp
    @Column(
            nullable = false
    )
    private LocalDateTime updatedAt;
}